name: MonPremierPlugin
main: com.votredomaine.MonPremierPlugin
version: 1.0.0
api-version: 1.20
description: >-
  Un plugin d'exemple minimal pour Spigot/Paper 1.20.
commands:
  gettnt:
    description: Donne un arc lanceur de TNT

